package main

import (
	"bufio"
	"bytes"
	"fmt"
	"go/format"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"strconv"
	"strings"
	"testing"

	"github.com/dlclark/regexp2/v2/syntax"
	"github.com/pkg/errors"
)

// TestConversion processes the file "testoutput1" from PCRE2 v10.21 (public domain).
//
// This generates one temporary Go test package containing all
// code-generated regex engines and a table-driven test for the PCRE cases. That keeps the
// expensive Go compile/link step to one generated package instead of one executable per pattern.
func TestConversion(t *testing.T) {
	patterns, err := parsePCRETestOutput("testoutput1")
	if err != nil {
		t.Fatal(err)
	}

	tempDir, err := os.MkdirTemp(".", ".pcre2harness-")
	if err != nil {
		t.Fatal(err)
	}
	//defer os.RemoveAll(tempDir) // nolint:errcheck

	var generated bytes.Buffer
	c, err := newConverter(&generated, "pcreharness")
	if err != nil {
		t.Fatal(errors.Wrap(err, "code generation error"))
	}

	harnessPatterns := make([]pcre2Pattern, 0, len(patterns))
	for i, pattern := range patterns {
		name := fmt.Sprintf("PCREPattern%d", i)
		if err := c.addRegexp("testoutput1", name, pattern.Pattern, pattern.Options, false, []string{getOptString(pattern.Options)}); err != nil {
			t.Errorf("code generation error for pattern %q: %v", pattern.Raw, err)
			continue
		}
		harnessPatterns = append(harnessPatterns, pattern)
	}
	if err := c.addFooter(); err != nil {
		t.Fatal(errors.Wrap(err, "code generation error"))
	}

	generatedPath := filepath.Join(tempDir, "pcre_codegen.go")
	if err := os.WriteFile(generatedPath, generated.Bytes(), 0o644); err != nil {
		t.Fatal(err)
	}

	testSource, err := buildPCREHarnessTestSource(harnessPatterns)
	if err != nil {
		t.Fatal(err)
	}
	testPath := filepath.Join(tempDir, "pcre_codegen_test.go")
	if err := os.WriteFile(testPath, testSource, 0o644); err != nil {
		t.Fatal(err)
	}

	goPath, err := exec.LookPath("go")
	if err != nil {
		t.Fatal(err)
	}
	cmd := exec.Command(goPath, "test", ".")
	cmd.Dir = tempDir
	out, err := cmd.CombinedOutput()
	if err != nil {
		t.Fatalf("generated PCRE harness failed:\n%s", out)
	}
}

type pcre2Pattern struct {
	Raw     string
	Pattern string
	Options syntax.RegexOptions
	Cases   []pcre2Case
}

type pcre2Case struct {
	Input    string
	NoMatch  bool
	Expected []string
}

var pcre2MatchGroup = regexp.MustCompile(`^\s*(\d+): (.*)`)

func parsePCRETestOutput(path string) ([]pcre2Pattern, error) {
	file, err := os.Open(path)
	if err != nil {
		return nil, err
	}
	defer file.Close() // nolint:errcheck

	var patterns []pcre2Pattern
	scanner := bufio.NewScanner(file)
	for scanner.Scan() {
		line := scanner.Text()

		if trim := strings.TrimSpace(line); trim == "" || strings.HasPrefix(trim, "#") {
			continue
		}

		patternStart := line[0]
		if patternStart != '/' && patternStart != '"' {
			return nil, fmt.Errorf("unknown file format, expected line to start with '/' or '\"', line in: %v", line)
		}

		rawPattern := line
		allowFirst := false
		for !containsEnder(line, patternStart, allowFirst) {
			if !scanner.Scan() {
				return nil, fmt.Errorf("unknown file format, expected more pattern text, but got EOF, pattern so far: %v", rawPattern)
			}
			line = scanner.Text()
			rawPattern += fmt.Sprintf("\n%s", line)
			allowFirst = true
		}

		pattern, err := parsePCREPattern(rawPattern)
		if err != nil {
			return nil, err
		}

		var current *pcre2Case
		for scanner.Scan() {
			line = scanner.Text()
			if strings.TrimSpace(line) == "" {
				if current != nil {
					pattern.Cases = append(pattern.Cases, *current)
				}
				current = nil
				break
			}

			switch {
			case strings.HasPrefix(line, "\\= Expect"):
				continue
			case strings.HasPrefix(line, "    "):
				if current != nil {
					pattern.Cases = append(pattern.Cases, *current)
				}
				current = &pcre2Case{
					Input: strings.TrimRight(line[4:], " "),
				}
			case strings.HasPrefix(line, "No match"):
				if current == nil {
					return nil, fmt.Errorf("no-match line without input for pattern %q", rawPattern)
				}
				current.NoMatch = true
			case pcre2MatchGroup.MatchString(line):
				if current == nil {
					return nil, fmt.Errorf("match group line without input for pattern %q: %s", rawPattern, line)
				}
				current.Expected = append(current.Expected, line)
			default:
				return nil, fmt.Errorf("unknown file format, expected match or match group but got %q", line)
			}
		}
		if current != nil {
			pattern.Cases = append(pattern.Cases, *current)
		}

		patterns = append(patterns, pattern)
	}
	if err := scanner.Err(); err != nil {
		return nil, err
	}

	return patterns, nil
}

func containsEnder(line string, ender byte, allowFirst bool) bool {
	index := strings.LastIndexByte(line, ender)
	if index > 0 {
		return true
	} else if index == 0 && allowFirst {
		return true
	}
	return false
}

func parsePCREPattern(rawPattern string) (pcre2Pattern, error) {
	index := strings.LastIndexAny(rawPattern, "/\"")
	if index < 0 {
		return pcre2Pattern{}, fmt.Errorf("pattern does not contain a closing delimiter: %q", rawPattern)
	}

	pattern := rawPattern
	var opts syntax.RegexOptions
	if index+1 < len(pattern) {
		textOptions := pattern[index+1:]
		pattern = pattern[:index+1]
		for _, textOpt := range strings.Split(textOptions, ",") {
			switch textOpt {
			case "dupnames":
			default:
				if strings.Contains(textOpt, "i") {
					opts |= syntax.IgnoreCase
				}
				if strings.Contains(textOpt, "s") {
					opts |= syntax.Singleline
				}
				if strings.Contains(textOpt, "m") {
					opts |= syntax.Multiline
				}
				if strings.Contains(textOpt, "x") {
					opts |= syntax.IgnorePatternWhitespace
				}
			}
		}
	}
	if len(pattern) < 2 {
		return pcre2Pattern{}, fmt.Errorf("pattern is missing delimiters: %q", rawPattern)
	}

	return pcre2Pattern{
		Raw:     rawPattern,
		Pattern: pattern[1 : len(pattern)-1],
		Options: opts,
	}, nil
}

func buildPCREHarnessTestSource(patterns []pcre2Pattern) ([]byte, error) {
	var buf bytes.Buffer
	buf.WriteString(`package pcreharness

import (
	"bytes"
	"fmt"
	"slices"
	"strings"
	"testing"

	"github.com/dlclark/regexp2/v2"
)

type pcreHarnessPattern struct {
	Raw     string
	Pattern string
	Options regexp2.RegexOptions
	Cases   []pcreHarnessCase
}

type pcreHarnessCase struct {
	Input    string
	NoMatch  bool
	Expected []string
}

var pcreHarnessPatterns = []pcreHarnessPattern{
`)
	for _, pattern := range patterns {
		fmt.Fprintf(&buf, "{Raw: %s, Pattern: %s, Options: regexp2.RegexOptions(%d), Cases: []pcreHarnessCase{\n",
			strconv.Quote(pattern.Raw),
			strconv.Quote(pattern.Pattern),
			int(pattern.Options),
		)
		for _, tc := range pattern.Cases {
			fmt.Fprintf(&buf, "{Input: %s, NoMatch: %t, Expected: []string{", strconv.Quote(tc.Input), tc.NoMatch)
			for _, expected := range tc.Expected {
				fmt.Fprintf(&buf, "%s,", strconv.Quote(expected))
			}
			buf.WriteString("}},\n")
		}
		buf.WriteString("}},\n")
	}
	buf.WriteString(`}

func TestGeneratedPCREConversion(t *testing.T) {
	for _, pattern := range pcreHarnessPatterns {
		pattern := pattern
		t.Run(pattern.Raw, func(t *testing.T) {
			re := regexp2.MustCompile(pattern.Pattern, pattern.Options)
			for _, tc := range pattern.Cases {
				tc := tc
				t.Run(tc.Input, func(t *testing.T) {
					lines, noMatch, err := runPCREHarnessCase(re, tc.Input)
					if err != nil {
						t.Fatal(err)
					}
					if tc.NoMatch {
						if !noMatch {
							t.Fatalf("expected no match for input %q, got %q", tc.Input, strings.Join(lines, "\n"))
						}
						return
					}
					if noMatch {
						t.Fatalf("expected match for input %q, got no match", tc.Input)
					}
					for _, expected := range tc.Expected {
						if !slices.Contains(lines, expected) {
							t.Fatalf("missing expected line %q for input %q; got %q", expected, tc.Input, strings.Join(lines, "\n"))
						}
					}
				})
			}
		})
	}
}

func runPCREHarnessCase(re *regexp2.Regexp, input string) ([]string, bool, error) {
	m, err := re.FindStringMatch(unEscapeToMatch(input))
	if err != nil {
		return nil, false, err
	}
	if m == nil {
		return nil, true, nil
	}

	g := m.Groups()
	lines := make([]string, len(g))
	for i := 0; i < len(g); i++ {
		val := "<unset>"
		if len(g[i].Captures) > 0 {
			val = unEscapeGroup(g[i].String())
		}
		lines[i] = fmt.Sprintf("%2v: %s", i, val)
	}
	return lines, false, nil
}

func unEscapeGroup(val string) string {
	buf := &bytes.Buffer{}

	for i := 0; i < len(val); i++ {
		ch := val[i]
		if ch <= 0x1f || ch >= 0x7f {
			fmt.Fprintf(buf, "\\x%.2x", ch)
		} else {
			buf.WriteByte(ch)
		}
	}

	return buf.String()
}

func unEscapeToMatch(line string) string {
	idx := strings.IndexRune(line, '\\')
	if idx == -1 {
		return line
	}

	buf := bytes.NewBufferString(line[:idx])
	inEscape := false
	for i := idx; i < len(line); i++ {
		ch := line[i]
		if ch == '\\' {
			if inEscape {
				buf.WriteByte(ch)
			}
			inEscape = !inEscape
			continue
		}
		if inEscape {
			switch ch {
			case 'x':
				buf.WriteByte(scanHex(line, &i))
			case 'a':
				buf.WriteByte(0x07)
			case 'b':
				buf.WriteByte('\b')
			case 'e':
				buf.WriteByte(0x1b)
			case 'f':
				buf.WriteByte('\f')
			case 'n':
				buf.WriteByte('\n')
			case 'r':
				buf.WriteByte('\r')
			case 't':
				buf.WriteByte('\t')
			case 'v':
				buf.WriteByte(0x0b)
			default:
				if ch >= '0' && ch <= '7' {
					buf.WriteByte(scanOctal(line, &i))
				} else {
					buf.WriteByte(ch)
				}
			}
			inEscape = false
		} else {
			buf.WriteByte(ch)
		}
	}

	return buf.String()
}

func scanHex(line string, idx *int) byte {
	if *idx >= len(line)-2 {
		panic(fmt.Sprintf("not enough hex chars in %v at %v", line, *idx))
	}
	(*idx)++
	d1 := hexDigit(line[*idx])
	(*idx)++
	d2 := hexDigit(line[*idx])
	if d1 < 0 || d2 < 0 {
		panic("bad hex chars")
	}

	return byte(d1*0x10 + d2)
}

func hexDigit(ch byte) int {
	if d := uint(ch - '0'); d <= 9 {
		return int(d)
	}
	if d := uint(ch - 'a'); d <= 5 {
		return int(d + 0xa)
	}
	if d := uint(ch - 'A'); d <= 5 {
		return int(d + 0xa)
	}
	return -1
}

func scanOctal(line string, idx *int) byte {
	c := 3
	if diff := len(line) - *idx; c > diff {
		c = diff
	}

	i := 0
	d := int(line[*idx] - '0')
	for c > 0 && d <= 7 {
		i *= 8
		i += d

		c--
		(*idx)++
		if *idx < len(line) {
			d = int(line[*idx] - '0')
		}
	}
	(*idx)--
	i &= 0xFF

	return byte(i)
}
`)

	return format.Source(buf.Bytes())
}
